[phases.setup]
nixPkgs = ["...", "php", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.bcmath", "php81Extensions.xml", "php81Extensions.curl", "php81Extensions.zip", "php81Extensions.gd", "php81Extensions.intl", "php81Extensions.tokenizer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
